/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdTemplateCreateRequest struct {
	// The name of the template (ex. Bronze Axe)
	Name string `json:"name"`
	// u96 Number as String (ex. 200000000) 
	Cap string `json:"cap"`
	// The type of custom contract to use for this template. Default will use a shared contract.
	ContractType string `json:"contractType,omitempty"`
	// FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)
	Type_ string `json:"type"`
	// Blockchain address to set as owner of the custom contract. Required if contractType is set.
	OwnerAddress string `json:"ownerAddress,omitempty"`
	Props *SdTemplateCreateRequestProps `json:"props"`
	// Returned to marketplaces as contract metadata
	PublicContractMetadata *interface{} `json:"publicContractMetadata,omitempty"`
}
