/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

// This is the data output json model
type SdGameGetResponse struct {
	// Game ID Number (unsigned 32 bit integer)
	Id int32 `json:"id"`
	// Game Owner ID
	OwnerId string `json:"ownerId"`
	// Game name
	Name string `json:"name"`
	// Game description
	Desc string `json:"desc"`
	// Game image
	Image string `json:"image"`
	// Game bucket name
	BucketName string `json:"bucketName"`
	// Game news
	News string `json:"news,omitempty"`
	Fees []SdGameGetResponseFees `json:"fees,omitempty"`
	// Game properties
	Props *interface{} `json:"props,omitempty"`
	// If on test mode features are enabled. Currently in development.
	TestMode bool `json:"testMode,omitempty"`
}
