/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

// This is the data output json model
type SdPlayerWalletGetResponse struct {
	// An array of player wallets on the blockchain
	Wallet []SdPlayerWalletGetResponseWallet `json:"wallet"`
}
