/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdPlayerWalletGetResponseWallet struct {
	// The name of the blockchain
	Blockchain string `json:"blockchain"`
	// The players blockchain Address
	Address string `json:"address"`
	// An array of the players balances on a given blockchain
	Monies []SdPlayerWalletGetResponseMonies `json:"monies,omitempty"`
}
