/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

// Data model for the /health response
type SdHealthResponse struct {
	// Connect to AWS subsystems worked properly, i.e. OK
	Status string `json:"status"`
}
