/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdPlayerMutateRequest struct {
	// Can be found with Player/getId(s).
	PlayerId string `json:"playerId"`
	// Specifies which properties you want to change (ex. {prop1: 5, prop2: 6, prop3: 7})
	Props *interface{} `json:"props"`
}
