/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdTemplateCreateBulk struct {
	// The name of the template (ex. Bronze Axe)
	Name string `json:"name"`
	// u96 Number as String (ex. 200000000), default 39614081257132168796771975168 
	Cap string `json:"cap,omitempty"`
	// The type of custom contract to use for this template. Default will use a shared contract.
	ContractType string `json:"contractType,omitempty"`
	// FT is a currency where every instance is the same, NFT is where every token instance differes (ex. FT)
	Type_ string `json:"type,omitempty"`
	// image url
	Image string `json:"image"`
	// Description of template
	Description string `json:"description,omitempty"`
	// Set if the Template is active or not
	ActiveListing bool `json:"activeListing,omitempty"`
	// Blockchain address to set as owner of the custom contract, if contractType is passed in.
	OwnerAddress string `json:"ownerAddress,omitempty"`
	Props *SdTemplateCreateBulkProps `json:"props,omitempty"`
	// Returned to marketplaces as contract metadata
	PublicContractMetadata *interface{} `json:"publicContractMetadata,omitempty"`
	// Inherited by tokens, and returned to marketplaces as token metadata
	PublicTokenMetadata *interface{} `json:"publicTokenMetadata,omitempty"`
}
