/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdTokenBurnRequest struct {
	// The Player's id, can be found with Player/getId(s). (ex. CzySggxVQz51jciGRFDY7d5BER2fav6TNEnPGjusPJPd)
	PlayerId string `json:"playerId"`
	// An an array of objects to burn (ex. [{tokenId: 5, amount: \"6\"}])
	TokenObjects []SdTokenBurnRequestTokenObjects `json:"tokenObjects"`
}
