/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdPlayerCreateRequest struct {
	// Identifier for the player
	UniqueId string `json:"uniqueId"`
	// URL of the player's image
	Image string `json:"image,omitempty"`
	// Metadata about the player
	UserData *interface{} `json:"userData"`
}
