/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

// This is the data output json model, i.e. {\"uniqueId\": \"playerId\"} 
type SdPlayerGetIdsResponse struct {
	// Player ID in the form of a UUID
	PlayerId string `json:"playerId"`
	// Player ID in the form of a the game player's internal playerId, i.e. email address, uuid
	UniqueId string `json:"uniqueId"`
}
