/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

// The Money object representation of the balance
type SdPlayerWalletGetResponseMonies struct {
	// The balance in minor units. ex: 2000000 for 2 coins USDC
	Amount string `json:"amount,omitempty"`
	// The currency code associated with the amount. ex: 'USDC'
	CurrencyCode string `json:"currencyCode,omitempty"`
}
