/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdTokenMintBulkTokenObject struct {
	// Specifies which Template you are creating an instance of (ex. 3)
	TemplateId int32 `json:"templateId"`
	// u64 Number as String, min: 0, max: 9223372036854775807 (ex. \"6\")
	Amount string `json:"amount"`
	Props *SdTokenMintBulkTokenObjectProps `json:"props,omitempty"`
	// Returned to marketplaces as token metadata
	PublicMetadata *interface{} `json:"publicMetadata,omitempty"`
}
