/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

// token data
type SdTokenGetResponse struct {
	// Game ID Number (unsigned 32 bit integer)
	GameId int32 `json:"gameId"`
	// Template ID Number (unsigned 32 bit integer)
	TemplateId int32 `json:"templateId"`
	// The ID of the token created
	Id int32 `json:"id"`
	// The name of the template
	Name string `json:"name,omitempty"`
	Flags int32 `json:"flags"`
	Props *SdTemplateGetTokensResponseTokenProps `json:"props"`
	// Game Owner's Public Key
	Owner string `json:"owner,omitempty"`
	// Returned to marketplaces as token metadata
	PublicMetadata *interface{} `json:"publicMetadata,omitempty"`
}
