/*
 * Stardust API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2023-02-22T22:32:07Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package stardust_core_sdk

type SdTemplateGetTokensResponsePlayer struct {
	// Player ID in the form of a UUID
	Id string `json:"id"`
	// Player ID in the form of a the game owner's internal playerId, i.e. email address
	UniqueId string `json:"uniqueId"`
	// URL of image cached by Stardust
	Image string `json:"image,omitempty"`
	// Timestamp of when a player was deleted
	DeletedAt string `json:"deletedAt,omitempty"`
}
